apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.AppName }}
  name: {{ .Values.AppName }}
  namespace: { { .Values.namespace.name } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: {{ .Values.AppName }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.AppName }}
    spec:
      containers:
        - image: { { .Values.image.repository } }: {{ .Values.image.tag }}
          name: techtrends
          imagePullPolicy: {{.Values.image.pullPolciy}}
          livenessProbe:            
            path: {{.Values.livenessProbe.path}}
            port: {{.Values.livenessProbe.port}}                        
          readinessProbe:            
            path:  {{.Values.livenessProbe.path}}
            port: {{.Values.livenessProbe.port}}             
          resources:
            requests:
              memory: {{.Values.resources.requests.memory}}
              cpu: {{.Values.resources.requests.cpu}}
            limits:
              memory: {{.Values.resources.limits.memory}}
              cpu: {{.Values.resources.limits.cpu}}
status: {}
